### ISSUE TITLE
Deprecations on Symfony 3.4

### ISSUE THREAD

**Issue by KoriSeng** [redjanym/FCMBundle#19]
Any fixes for this? Right now i am using a really stupid method

```yml
services:
    redjan_ym_fcm.client:
        alias: RedjanYm\FCMBundle\FCMClient
        public: true

    RedjanYm\FCMBundle\FCMClient:
        arguments: ['@sngrl.firebase_php_notification']
```

Unless this is the actual way of doing things??
