### ISSUE TITLE
Allow Send Push for two different firebase application

### ISSUE THREAD

**Issue by bodva** [redjanym/FCMBundle#28]
Hi! 
Is there is a way to send push notification from one symfony backend to the two different firebase application? I have one backend for two kinds of application and need this kind of opportunity.

**Comment by redjanym** [comment]
Hi, 
this is not a standard usage of the bundle but via a workaround it can be done using the standard configuration of the bundle as the Firebase Application 1 and creating a second service for the FCMClient with another server key and using it as Firebase Application 2.

Keep in mind, you need to follow the standard config of the bundle as in the documentation provided for having the first Firebase App.

**Creating a second service**
In the service.yml of your app add this two services:
```yml
services:
    redjan_ym_fcm.client_2:
        class: RedjanYm\FCMBundle\FCMClient
        public: true
        arguments: ['@sngrl.firebase_php_notification_2']

    sngrl.firebase_php_notification_2:
        class: sngrl\PhpFirebaseCloudMessaging\Client
        calls:
            - [setApiKey, ['YOUR_FIREBASE_SECOND_SERVER_KEY']]
```

This would build another FCMClient service called ```redjan_ym_fcm.client_2``` which can be called via the Service Container like the first service.
```php
  $fcmClient2 = $this->getContainer()->get('redjan_ym_fcm.client_2');
```
This service will point to your second firebase app. 

Have a try and let me know if all is working.
