### ISSUE TITLE
FCMBundle works with symfony 4.4

### ISSUE THREAD

**Issue by davart87** [redjanym/FCMBundle#32]
Is that possible to use this bundle for symfony version 4.4 ?

**Comment by redjanym** [comment]
Sorry for the late reply. Hope this helps you or someone else in the future. In the current version the bundle doesn't create a config file automatically for Symfony 4 or higher. Instead before installing the bundle you need to create a file with the configuration:

```yaml
# config/redjan_ym_fcm.yaml

redjan_ym_fcm:
  firebase_api_key: "sdadasdasdasdasd245sadas5d4a8sd2d5as4d8s"

```

Then require the bundle:

```
composer require redjanym/fcm-bundle
```
